// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/calculator/calculator_service.proto

package kae.experimental.calculator;

public final class CalculatorServiceProtos {
  private CalculatorServiceProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SumRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kae.experimental.calculator.SumRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated int32 addends = 1;</code>
     * @return A list containing the addends.
     */
    java.util.List<java.lang.Integer> getAddendsList();
    /**
     * <code>repeated int32 addends = 1;</code>
     * @return The count of addends.
     */
    int getAddendsCount();
    /**
     * <code>repeated int32 addends = 1;</code>
     * @param index The index of the element to return.
     * @return The addends at the given index.
     */
    int getAddends(int index);
  }
  /**
   * Protobuf type {@code kae.experimental.calculator.SumRequest}
   */
  public static final class SumRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:kae.experimental.calculator.SumRequest)
      SumRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SumRequest.newBuilder() to construct.
    private SumRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SumRequest() {
      addends_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SumRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SumRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                addends_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              addends_.addInt(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                addends_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                addends_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          addends_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kae.experimental.calculator.CalculatorServiceProtos.internal_static_kae_experimental_calculator_SumRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kae.experimental.calculator.CalculatorServiceProtos.internal_static_kae_experimental_calculator_SumRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kae.experimental.calculator.CalculatorServiceProtos.SumRequest.class, kae.experimental.calculator.CalculatorServiceProtos.SumRequest.Builder.class);
    }

    public static final int ADDENDS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.IntList addends_;
    /**
     * <code>repeated int32 addends = 1;</code>
     * @return A list containing the addends.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
        getAddendsList() {
      return addends_;
    }
    /**
     * <code>repeated int32 addends = 1;</code>
     * @return The count of addends.
     */
    public int getAddendsCount() {
      return addends_.size();
    }
    /**
     * <code>repeated int32 addends = 1;</code>
     * @param index The index of the element to return.
     * @return The addends at the given index.
     */
    public int getAddends(int index) {
      return addends_.getInt(index);
    }
    private int addendsMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (getAddendsList().size() > 0) {
        output.writeUInt32NoTag(10);
        output.writeUInt32NoTag(addendsMemoizedSerializedSize);
      }
      for (int i = 0; i < addends_.size(); i++) {
        output.writeInt32NoTag(addends_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < addends_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(addends_.getInt(i));
        }
        size += dataSize;
        if (!getAddendsList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        addendsMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kae.experimental.calculator.CalculatorServiceProtos.SumRequest)) {
        return super.equals(obj);
      }
      kae.experimental.calculator.CalculatorServiceProtos.SumRequest other = (kae.experimental.calculator.CalculatorServiceProtos.SumRequest) obj;

      if (!getAddendsList()
          .equals(other.getAddendsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAddendsCount() > 0) {
        hash = (37 * hash) + ADDENDS_FIELD_NUMBER;
        hash = (53 * hash) + getAddendsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kae.experimental.calculator.CalculatorServiceProtos.SumRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kae.experimental.calculator.CalculatorServiceProtos.SumRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code kae.experimental.calculator.SumRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:kae.experimental.calculator.SumRequest)
        kae.experimental.calculator.CalculatorServiceProtos.SumRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kae.experimental.calculator.CalculatorServiceProtos.internal_static_kae_experimental_calculator_SumRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kae.experimental.calculator.CalculatorServiceProtos.internal_static_kae_experimental_calculator_SumRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kae.experimental.calculator.CalculatorServiceProtos.SumRequest.class, kae.experimental.calculator.CalculatorServiceProtos.SumRequest.Builder.class);
      }

      // Construct using kae.experimental.calculator.CalculatorServiceProtos.SumRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        addends_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kae.experimental.calculator.CalculatorServiceProtos.internal_static_kae_experimental_calculator_SumRequest_descriptor;
      }

      @java.lang.Override
      public kae.experimental.calculator.CalculatorServiceProtos.SumRequest getDefaultInstanceForType() {
        return kae.experimental.calculator.CalculatorServiceProtos.SumRequest.getDefaultInstance();
      }

      @java.lang.Override
      public kae.experimental.calculator.CalculatorServiceProtos.SumRequest build() {
        kae.experimental.calculator.CalculatorServiceProtos.SumRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public kae.experimental.calculator.CalculatorServiceProtos.SumRequest buildPartial() {
        kae.experimental.calculator.CalculatorServiceProtos.SumRequest result = new kae.experimental.calculator.CalculatorServiceProtos.SumRequest(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) != 0)) {
          addends_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.addends_ = addends_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kae.experimental.calculator.CalculatorServiceProtos.SumRequest) {
          return mergeFrom((kae.experimental.calculator.CalculatorServiceProtos.SumRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kae.experimental.calculator.CalculatorServiceProtos.SumRequest other) {
        if (other == kae.experimental.calculator.CalculatorServiceProtos.SumRequest.getDefaultInstance()) return this;
        if (!other.addends_.isEmpty()) {
          if (addends_.isEmpty()) {
            addends_ = other.addends_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAddendsIsMutable();
            addends_.addAll(other.addends_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kae.experimental.calculator.CalculatorServiceProtos.SumRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kae.experimental.calculator.CalculatorServiceProtos.SumRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.Internal.IntList addends_ = emptyIntList();
      private void ensureAddendsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          addends_ = mutableCopy(addends_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated int32 addends = 1;</code>
       * @return A list containing the addends.
       */
      public java.util.List<java.lang.Integer>
          getAddendsList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(addends_) : addends_;
      }
      /**
       * <code>repeated int32 addends = 1;</code>
       * @return The count of addends.
       */
      public int getAddendsCount() {
        return addends_.size();
      }
      /**
       * <code>repeated int32 addends = 1;</code>
       * @param index The index of the element to return.
       * @return The addends at the given index.
       */
      public int getAddends(int index) {
        return addends_.getInt(index);
      }
      /**
       * <code>repeated int32 addends = 1;</code>
       * @param index The index to set the value at.
       * @param value The addends to set.
       * @return This builder for chaining.
       */
      public Builder setAddends(
          int index, int value) {
        ensureAddendsIsMutable();
        addends_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 addends = 1;</code>
       * @param value The addends to add.
       * @return This builder for chaining.
       */
      public Builder addAddends(int value) {
        ensureAddendsIsMutable();
        addends_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 addends = 1;</code>
       * @param values The addends to add.
       * @return This builder for chaining.
       */
      public Builder addAllAddends(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureAddendsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, addends_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int32 addends = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAddends() {
        addends_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:kae.experimental.calculator.SumRequest)
    }

    // @@protoc_insertion_point(class_scope:kae.experimental.calculator.SumRequest)
    private static final kae.experimental.calculator.CalculatorServiceProtos.SumRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kae.experimental.calculator.CalculatorServiceProtos.SumRequest();
    }

    public static kae.experimental.calculator.CalculatorServiceProtos.SumRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SumRequest>
        PARSER = new com.google.protobuf.AbstractParser<SumRequest>() {
      @java.lang.Override
      public SumRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SumRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SumRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SumRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public kae.experimental.calculator.CalculatorServiceProtos.SumRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SumResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:kae.experimental.calculator.SumResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 sum = 1;</code>
     * @return The sum.
     */
    int getSum();
  }
  /**
   * Protobuf type {@code kae.experimental.calculator.SumResponse}
   */
  public static final class SumResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:kae.experimental.calculator.SumResponse)
      SumResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SumResponse.newBuilder() to construct.
    private SumResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SumResponse() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SumResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SumResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              sum_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kae.experimental.calculator.CalculatorServiceProtos.internal_static_kae_experimental_calculator_SumResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kae.experimental.calculator.CalculatorServiceProtos.internal_static_kae_experimental_calculator_SumResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kae.experimental.calculator.CalculatorServiceProtos.SumResponse.class, kae.experimental.calculator.CalculatorServiceProtos.SumResponse.Builder.class);
    }

    public static final int SUM_FIELD_NUMBER = 1;
    private int sum_;
    /**
     * <code>int32 sum = 1;</code>
     * @return The sum.
     */
    @java.lang.Override
    public int getSum() {
      return sum_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sum_ != 0) {
        output.writeInt32(1, sum_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sum_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, sum_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof kae.experimental.calculator.CalculatorServiceProtos.SumResponse)) {
        return super.equals(obj);
      }
      kae.experimental.calculator.CalculatorServiceProtos.SumResponse other = (kae.experimental.calculator.CalculatorServiceProtos.SumResponse) obj;

      if (getSum()
          != other.getSum()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SUM_FIELD_NUMBER;
      hash = (53 * hash) + getSum();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static kae.experimental.calculator.CalculatorServiceProtos.SumResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static kae.experimental.calculator.CalculatorServiceProtos.SumResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(kae.experimental.calculator.CalculatorServiceProtos.SumResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code kae.experimental.calculator.SumResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:kae.experimental.calculator.SumResponse)
        kae.experimental.calculator.CalculatorServiceProtos.SumResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return kae.experimental.calculator.CalculatorServiceProtos.internal_static_kae_experimental_calculator_SumResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return kae.experimental.calculator.CalculatorServiceProtos.internal_static_kae_experimental_calculator_SumResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                kae.experimental.calculator.CalculatorServiceProtos.SumResponse.class, kae.experimental.calculator.CalculatorServiceProtos.SumResponse.Builder.class);
      }

      // Construct using kae.experimental.calculator.CalculatorServiceProtos.SumResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sum_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return kae.experimental.calculator.CalculatorServiceProtos.internal_static_kae_experimental_calculator_SumResponse_descriptor;
      }

      @java.lang.Override
      public kae.experimental.calculator.CalculatorServiceProtos.SumResponse getDefaultInstanceForType() {
        return kae.experimental.calculator.CalculatorServiceProtos.SumResponse.getDefaultInstance();
      }

      @java.lang.Override
      public kae.experimental.calculator.CalculatorServiceProtos.SumResponse build() {
        kae.experimental.calculator.CalculatorServiceProtos.SumResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public kae.experimental.calculator.CalculatorServiceProtos.SumResponse buildPartial() {
        kae.experimental.calculator.CalculatorServiceProtos.SumResponse result = new kae.experimental.calculator.CalculatorServiceProtos.SumResponse(this);
        result.sum_ = sum_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof kae.experimental.calculator.CalculatorServiceProtos.SumResponse) {
          return mergeFrom((kae.experimental.calculator.CalculatorServiceProtos.SumResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(kae.experimental.calculator.CalculatorServiceProtos.SumResponse other) {
        if (other == kae.experimental.calculator.CalculatorServiceProtos.SumResponse.getDefaultInstance()) return this;
        if (other.getSum() != 0) {
          setSum(other.getSum());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        kae.experimental.calculator.CalculatorServiceProtos.SumResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (kae.experimental.calculator.CalculatorServiceProtos.SumResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int sum_ ;
      /**
       * <code>int32 sum = 1;</code>
       * @return The sum.
       */
      @java.lang.Override
      public int getSum() {
        return sum_;
      }
      /**
       * <code>int32 sum = 1;</code>
       * @param value The sum to set.
       * @return This builder for chaining.
       */
      public Builder setSum(int value) {
        
        sum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 sum = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSum() {
        
        sum_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:kae.experimental.calculator.SumResponse)
    }

    // @@protoc_insertion_point(class_scope:kae.experimental.calculator.SumResponse)
    private static final kae.experimental.calculator.CalculatorServiceProtos.SumResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new kae.experimental.calculator.CalculatorServiceProtos.SumResponse();
    }

    public static kae.experimental.calculator.CalculatorServiceProtos.SumResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SumResponse>
        PARSER = new com.google.protobuf.AbstractParser<SumResponse>() {
      @java.lang.Override
      public SumResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SumResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SumResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SumResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public kae.experimental.calculator.CalculatorServiceProtos.SumResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kae_experimental_calculator_SumRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kae_experimental_calculator_SumRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kae_experimental_calculator_SumResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kae_experimental_calculator_SumResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)proto/calculator/calculator_service.pr" +
      "oto\022\033kae.experimental.calculator\"\035\n\nSumR" +
      "equest\022\017\n\007addends\030\001 \003(\005\"\032\n\013SumResponse\022\013" +
      "\n\003sum\030\001 \001(\0052m\n\021CalculatorService\022X\n\003Sum\022" +
      "\'.kae.experimental.calculator.SumRequest" +
      "\032(.kae.experimental.calculator.SumRespon" +
      "seB.B\027CalculatorServiceProtosZ\023golang/ca" +
      "lculatorpbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_kae_experimental_calculator_SumRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kae_experimental_calculator_SumRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kae_experimental_calculator_SumRequest_descriptor,
        new java.lang.String[] { "Addends", });
    internal_static_kae_experimental_calculator_SumResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kae_experimental_calculator_SumResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kae_experimental_calculator_SumResponse_descriptor,
        new java.lang.String[] { "Sum", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
